<script>
  export let src = '/image.png';
  export let alt = `Background generated by AI.`;

  import { onMount } from 'svelte';
  import { averageColor } from '../scripts/colors';

  let backgroundImage;

  onMount(() => {
    loaded();
  });

  const loaded = async () => {
    await averageColor(backgroundImage);
  };
</script>

<div
  class="bg hidden lg:block min-h-screen max-h-screen opacity-[var(--ready)]"
>
  <img
    on:load={loaded}
    bind:this={backgroundImage}
    {src}
    {alt}
    class="object-cover min-h-screen w-full"
  />
</div>
